<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;
use App\Models\User;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get admin user dynamically
        $year = date('Y');
        $adminUser = User::where('email', "RGC-{$year}-0001@rgc.org")->first();
        $createdBy = $adminUser ? $adminUser->id : 1;

        $events = [
            // Past Events
            [
                'title' => 'Ibada ya Mwaka Mpya',
                'description' => 'Ibada maalum ya kumkaribisha mwaka mpya 2025. Tutashukuru kwa mwaka uliopita na kuomba baraka za mwaka mpya.',
                'event_type' => 'Ibada',
                'event_date' => '2025-01-01',
                'start_time' => '09:00:00',
                'end_time' => '12:00:00',
                'venue' => 'Kanisa Kuu - Mtaa wa RGC',
                'expected_attendance' => 300,
                'actual_attendance' => 285,
                'budget' => 500000,
                'is_active' => true,
                'notes' => 'Sherehe kubwa ya mwaka mpya iliyofanyika kwa mafanikio',
                'created_by' => $createdBy,
                'created_at' => Carbon::now()->subMonths(6),
            ],
            [
                'title' => 'Semina ya Viongozi wa Kanisa',
                'description' => 'Semina ya kuimarisha uongozi wa kanisa. Mada: "Uongozi wa Kikristo katika Karne ya 21"',
                'event_type' => 'Semina',
                'event_date' => Carbon::now()->subMonths(2)->format('Y-m-d'),
                'start_time' => '08:00:00',
                'end_time' => '17:00:00',
                'venue' => 'Jumba la Jimbo',
                'expected_attendance' => 50,
                'actual_attendance' => 48,
                'budget' => 450000,
                'is_active' => true,
                'notes' => 'Semina iliyofanyika kwa mafanikio. Viongozi wote walihudhuhudhuria',
                'created_by' => $createdBy,
                'created_at' => Carbon::now()->subMonths(3),
            ],
            [
                'title' => 'Tamasha la Vijana',
                'description' => 'Tamasha la vijana wa kanisa - michezo, burudani na elimu ya kiroho',
                'event_type' => 'Michezo',
                'event_date' => Carbon::now()->subMonths(4)->format('Y-m-d'),
                'start_time' => '07:00:00',
                'end_time' => '18:00:00',
                'venue' => 'Uwanja wa Michezo - Goba',
                'expected_attendance' => 120,
                'actual_attendance' => 135,
                'budget' => 600000,
                'is_active' => true,
                'notes' => 'Tamasha lililofaulu sana. Vijana wengi walishiriki',
                'created_by' => $createdBy,
                'created_at' => Carbon::now()->subMonths(5),
            ],
            [
                'title' => 'Ibada ya Pasaka',
                'description' => 'Sherehe ya Pasaka - Kumbukumbu ya Kifo na Ufufuo wa Yesu Kristo',
                'event_type' => 'Ibada',
                'event_date' => '2025-04-20',
                'start_time' => '06:00:00',
                'end_time' => '10:00:00',
                'venue' => 'Kanisa Kuu - Mtaa wa RGC',
                'expected_attendance' => 400,
                'actual_attendance' => 420,
                'budget' => 800000,
                'is_active' => true,
                'notes' => 'Ibada ya Pasaka iliyofanyika kwa shangwe kubwa',
                'created_by' => $createdBy,
                'created_at' => Carbon::now()->subMonths(5),
            ],

            // Upcoming Events
            [
                'title' => 'Ibada ya Jumapili',
                'description' => 'Ibada ya kawaida ya Jumapili - Saa 3 asubuhi',
                'event_type' => 'Ibada',
                'event_date' => Carbon::now()->next('Sunday')->format('Y-m-d'),
                'start_time' => '09:00:00',
                'end_time' => '12:00:00',
                'venue' => 'Kanisa Kuu - Mtaa wa RGC',
                'expected_attendance' => 250,
                'actual_attendance' => null,
                'budget' => 100000,
                'is_active' => true,
                'notes' => 'Ibada ya kawaida ya kila Jumapili',
                'created_by' => $createdBy,
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Mkutano wa Wazazi',
                'description' => 'Mkutano wa wazazi wa watoto wanaosoma shule ya Jumapili. Kujadili maendeleo ya watoto.',
                'event_type' => 'Mkutano',
                'event_date' => Carbon::now()->addDays(5)->format('Y-m-d'),
                'start_time' => '15:00:00',
                'end_time' => '17:00:00',
                'venue' => 'Ukumbi wa Kanisa',
                'expected_attendance' => 80,
                'actual_attendance' => null,
                'budget' => 150000,
                'is_active' => true,
                'notes' => 'Mkutano muhimu wa wazazi na waalimu',
                'created_by' => $createdBy,
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Maombi ya Usiku (Kesha)',
                'description' => 'Kesha ya maombi - Kuomba kwa ajili ya kanisa na taifa',
                'event_type' => 'Kesha',
                'event_date' => Carbon::now()->addDays(10)->format('Y-m-d'),
                'start_time' => '21:00:00',
                'end_time' => '05:00:00',
                'venue' => 'Kanisa Kuu - Mtaa wa RGC',
                'expected_attendance' => 150,
                'actual_attendance' => null,
                'budget' => 200000,
                'is_active' => true,
                'notes' => 'Kesha ya kila mwezi - Jumamosi ya pili',
                'created_by' => $createdBy,
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Crusade ya Injili - Mkoa wa Dar',
                'description' => 'Crusade ya injili kwa pamoja na mitaa mingine. Wahubiri kutoka nje watahudhudhuria.',
                'event_type' => 'Crusade',
                'event_date' => Carbon::now()->addDays(15)->format('Y-m-d'),
                'start_time' => '16:00:00',
                'end_time' => '20:00:00',
                'venue' => 'Uwanja wa Jamii - Mbezi Beach',
                'expected_attendance' => 500,
                'actual_attendance' => null,
                'budget' => 1500000,
                'is_active' => true,
                'notes' => 'Crusade kubwa ya kusambaza injili kwa watu wengi',
                'created_by' => $createdBy,
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Mahubiri ya Bibilia - Mwisho wa Wiki',
                'description' => 'Mahubiri maalum ya mafundisho ya Bibilia - Mwalimu kutoka Jimbo',
                'event_type' => 'Mahubiri',
                'event_date' => Carbon::now()->addDays(20)->format('Y-m-d'),
                'start_time' => '14:00:00',
                'end_time' => '17:00:00',
                'venue' => 'Kanisa Kuu - Mtaa wa RGC',
                'expected_attendance' => 200,
                'actual_attendance' => null,
                'budget' => 250000,
                'is_active' => true,
                'notes' => 'Mafundisho maalum ya Bibilia',
                'created_by' => $createdBy,
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Ubatizo wa Watoto',
                'description' => 'Ibada maalum ya Ubatizo wa watoto wachanga. Familia 15 zitashiriki.',
                'event_type' => 'Ibada',
                'event_date' => Carbon::now()->addDays(25)->format('Y-m-d'),
                'start_time' => '10:00:00',
                'end_time' => '13:00:00',
                'venue' => 'Kanisa Kuu - Mtaa wa RGC',
                'expected_attendance' => 180,
                'actual_attendance' => null,
                'budget' => 300000,
                'is_active' => true,
                'notes' => 'Sherehe ya ubatizo wa watoto 20',
                'created_by' => $createdBy,
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Mkutano wa Akina Mama',
                'description' => 'Mkutano wa kila mwezi wa kundi la akina mama. Mada: Ujenzi wa familia imara',
                'event_type' => 'Mkutano',
                'event_date' => Carbon::now()->addDays(12)->format('Y-m-d'),
                'start_time' => '14:00:00',
                'end_time' => '16:30:00',
                'venue' => 'Ukumbi wa Kanisa',
                'expected_attendance' => 100,
                'actual_attendance' => null,
                'budget' => 120000,
                'is_active' => true,
                'notes' => 'Mkutano wa kawaida wa akina mama',
                'created_by' => $createdBy,
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Safari ya Wazee - Mikumi',
                'description' => 'Safari ya kitalii ya wazee wa kanisa kwenda Mikumi kwa siku 3',
                'event_type' => 'Safari',
                'event_date' => Carbon::now()->addDays(30)->format('Y-m-d'),
                'start_time' => '06:00:00',
                'end_time' => '18:00:00',
                'venue' => 'Mikumi National Park',
                'expected_attendance' => 45,
                'actual_attendance' => null,
                'budget' => 2000000,
                'is_active' => true,
                'notes' => 'Safari ya burudani na kujifurahisha kwa wazee',
                'created_by' => $createdBy,
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Sherehe ya Mavuno',
                'description' => 'Sherehe kuu ya mavuno - Kuchukua mazao ya kwanza kwa Mungu',
                'event_type' => 'Sherehe',
                'event_date' => Carbon::now()->addDays(45)->format('Y-m-d'),
                'start_time' => '08:00:00',
                'end_time' => '14:00:00',
                'venue' => 'Kanisa Kuu - Mtaa wa RGC',
                'expected_attendance' => 450,
                'actual_attendance' => null,
                'budget' => 1200000,
                'is_active' => true,
                'notes' => 'Sherehe kubwa ya mwaka - Mavuno',
                'created_by' => $createdBy,
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Kikao cha Kamati ya Ujenzi',
                'description' => 'Kikao cha kamati ya ujenzi kujadili miradi ya ukarabati',
                'event_type' => 'Kikao',
                'event_date' => Carbon::now()->addDays(7)->format('Y-m-d'),
                'start_time' => '18:00:00',
                'end_time' => '20:00:00',
                'venue' => 'Ofisi ya Kanisa',
                'expected_attendance' => 12,
                'actual_attendance' => null,
                'budget' => 50000,
                'is_active' => true,
                'notes' => 'Kikao cha kila mwezi cha kamati ya ujenzi',
                'created_by' => $createdBy,
                'created_at' => Carbon::now(),
            ],
        ];

        foreach ($events as $event) {
            Event::create($event);
        }

        $this->command->info('✓ ' . count($events) . ' matukio yameongezwa successfully!');
    }
}
